:description: Anonymous comments, taken from reddit, discord, twitter, and our feedback system.
:lastUpdated: false
:name: Feedback
:next: false
:outline: false
:prev: false

=== Feedback

*Anonymous comments, taken from reddit, discord, twitter, and our feedback system. This is why we do it. People are the motivation, equality is the goal.*

'''

* _"Before finding this, I've been searching google myself and have experienced viruses, fake info, and just bad advice. But the amazing guides and links on FMHY really make it so much safer and simpler to find the things I need. I'm sort of the tech person in my family, so it saves me from so much testing and work."_
* _"Your sources have allowed me to give my father whatever shows or movies he asks for. Old stuff from when he was younger and all that. Stuff I wouldn't be able to access otherwise. It means a lot since he had heart surgery in Feb 2020 and cant really do much anymore, so its one of the few ways he can keep himself busy. Thank you."_
* _"That's why I love FMHY so much. Before id spend hours and hours every day trying to hunt useful websites for myself."_
* _"I love this website so much. I literally have it labelled as "Everything" in my favorites."_
* _"No bullshit, and has all the info I need to gain free access to media."_
* _"Y'all have helped not only me but my friends through college and the pandemic in ways you all probably don't even realize."_
* _"thank you so much for this effort, guys, you are amazing, I stopped searching on google for stuff and got addicted to your website, keep going :)"_
* _"Literally, when I need something, all I need to do is check here first! thank you for being here, for being access to everyone and anyone, I really really appreciate it!"_
* _"I want to express my sincere appreciation for the wiki of useful resources. It has proven to be an invaluable source of information, providing a wide range of knowledge on various topics. The well-organized and comprehensive nature of the wiki has been instrumental in aiding my research and learning. I am truly grateful for the effort and dedication that has gone into curating and maintaining such a valuable repository of knowledge. Thank you for this exceptional resource."_
* _"Amazing stuff. Spent almost whole day browsing this and I got introduced to tons of great software. Thank you!!"_
* _"I love FMHY's wiki, to the point I can't use the internet without it."_
* _"This wiki is one of the best out there, seriously. Keep up the great work!"_
* _"I love having an extreme amount of privacy. And it's not just for piracy, so this is REALLY useful. Thanks!"_
* _"Every person I share this sub with is always completely grateful, and it's no wonder why."_
