= Our stance on Download Pirate
:aside: left
:date: 2024-02-18
:description: Download Pirate
:footer: true
:next: false
:prev: false
:sidebar: false

+++<Post authors="['nbats']">++++++</Post>+++

For those of you who don't know, the VFX site Download Pirate was removed by /r/Piracy and placed in their unsafe list following this https://redd.it/1aswsl7[thread]. According to the post, OP downloaded Adobe Acrobat and got a pretty nasty trojan.

To test this we downloaded it and https://ibb.co/rGHXT0w[checked the checksum] of each of the files compared to m0nkrus, and they match exactly. Its hard to say what happened to OP, but it seems pretty likely that they got the trojan from something other than Download Pirate.

If someone has a virustotal scan, or some sort of proof Download Pirate is malicious please https://redd.it/1atkloc[let us know].

'''

*update* - Here's a setup scan thanks to /u/LichessLuvr which seems to be clean: https://www.virustotal.com/gui/file/04889538532f10f910029a5ef65068aed713019fb50462546e82ee8ced81350b[Adobe Acrobat Pro DC 2023 v23.8.20421 x64]

'''

*update 2* - We just scanned all of the https://ibb.co/VxBwzN3[patched files] and they came back clean too, so this is unlikely to have malware unless its hidden really well within the ISO. OP either got malware from an ad on the file host or already had the trojan before installing Acrobat.

We're still open to new evidence if someone comes forward with it, but for now we can't find any reason to think they're malicious so we're going to keep them in FMHY. The version OP downloaded is v23.8.20421 from 1cloudfile if someone wants to check it themselves.
