= Minecraft Server
:aside: left
:date: 2024-02-11
:description: Minecraft Server
:doctype: book
:footer: true
:next: false
:prev: false
:sidebar: false

+++<Post authors="['nbats']">++++++</Post>+++

= Join at: `fmhy.net`

'''

* You will be spawned at the hub.
* To go to vanilla, head to the end portal.
* To go to modded, head to the nether portal.
* Modded requires Minecraft 1.20.1 Forge.
* Vanilla requires Minecraft 1.20.4.

'''

[discrete]
=== Mod Downloads

*Attached is the mod pack for modded*: https://buzzheavier.com/f/GIr%2FvkDOsAA=[RAR] + https://rentry.org/fmhy-modded[Guide]
or you could use the .mrpack files and add it to Prism or other compatible launchers:

https://cdn.discordapp.com/attachments/1207087196327120896/1218042133382959184/FMHY_Modpack-2.mrpack?ex=66063922&is=65f3c422&hm=a3fecfe897d81368f91f6860f96e5359706c292269bafd82429d72b5323bf1a1[FMHY_Modpack-2.mrpack]

https://cdn.discordapp.com/attachments/1207087196327120896/1218063597326827571/FMHY_Server_Pack_ClientPP.mrpack?ex=66064d20&is=65f3d820&hm=a2476bc723343c912bd4ab9e549bcfa0338c68ff0b670c266d4b1dbaabd3d032[FMHY_Server_Pack_ClientPP.mrpack]

https://buzzheavier.com/f/GIr+b3jOsAA=[Optional Modpack with QOL mods added]

'''

[discrete]
=== Things to Know

* If it times out when joining then just try rejoining again.
* If you get stuck in the lobby, use the command `/server modded` or``/server survival`` to join.
* If you can't break blocks or it's glitching, you are probably too close to the spawn and need to go farther.
* (Modded) To set a skin, use the `/skin` command.
* To hide yourself from being shown in Dynmap, run this command `/dynmap hide`.
* For modded 6GB+ RAM is required, but 12GB+ is recommended.
* Simple Voice Chat mod is supported on Modded and (optional) Vanilla servers.

Have fun! ♥
